language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - release

before_install:
  - export PATH=$PATH:$HOME/gopath/bin

matrix:
  allow_failures:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: release

script:
 - go test -v ./...